# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Erik Solis
name: Erik Solis
description: Game Dev blog/portfolio for Erik Solis!
email: eriksolis1024@gmail.com
# logo: "/assets/images/strum.jpg"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/eriks-portfolio" # the subpath of your site, e.g. /blog
url: "https://eriksolis.github.io/eriks-portfolio" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  eriksolis
locale: en-US
icon: /assets/images/strum.jpg

include: ["_pages"]


defaults:
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      breadcrumbs: true
      author_profile: true
      share: false
      

  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false

  - scope:
      path: ""
      type: collection
    values:
      breadcrumbs: true



author:
    name     :  Erik Solis
    avatar   : /assets/images/strum.jpg
    bio      : "Game Dev.\n  B.S (CS) Conc. Game Development"
    location : San Jose, CA
    links:
        - label: Email
          icon: fa-regular fa-fw fa-envelope
          url: mailto:eriksolisschool@gmail.com
        - label: LinkedIn
          icon: fab fa-linkedin
          url: https://www.linkedin.com/in/erik-solis-396a2b331/
        - label: GitHub
          icon: fab fa-fw fa-github
          url: https://github.com/eriksolis
        - label: Itch.io
          icon: fab fa-fw fa-itch-io
          url: https://strumboid.itch.io/


# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eriksolis"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/erik-solis-396a2b331/"
    - label: Itch.io
      icon: fab fa-fw fa-itch-io
      url: https://strumboid.itch.io/
  since: "2026"

    
collections:
  projects:
    output: true
    permalink: /:collection/:path/


# Build settings
# theme: minima
# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes 
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-archives
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
